version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - ">= 0"
  - dependency-name: electron-settings
    versions:
    - ">= 0"
  - dependency-name: less
    versions:
    - ">= 0"
