name: appium-desktop
version: 1.12.1
summary: Appium Desktop Client for Linux
description: | 
 An Appium Server and Inspector in Desktop GUIs. 
confinement: strict
grade: stable
icon: snap/gui/appium.png

apps:
  appium-desktop:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/appium-desktop
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: dist/linux-unpacked
    after:
      - desktop-gtk2
