# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript
parameters:
  name: ''
  pool: ''
  xvfb: false
  target: ''
jobs:
  - job: ${{parameters.name}}
    pool: ${{parameters.pool}}
    variables:
      PYTHON_ENV: 'python'
      TARGET: ${{ parameters.target }}
      E2E_TIMEOUT: 600000
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '11.x'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run build
      displayName: Build project
    - script: npx build --publish onTagOrDraft
      displayName: Build application bundles
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: release/