# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript
parameters:
  name: ''
  pool: ''
  xvfb: false
  target: ''
jobs:
  - job: ${{parameters.name}}
    pool: ${{parameters.pool}}
    variables:
      PYTHON_ENV: 'python'
      TARGET: ${{ parameters.target }}
      E2E_TIMEOUT: 600000
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '11.x'
    - ${{ if eq(parameters.xvfb, 'true') }}:
      - script: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        displayName: XVFB
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run build
      displayName: Build project
    - script: npm test
      displayName: NPM test
    - ${{ if eq(parameters.e2e, 'true') }}:
      - script: npm run e2e
        displayName: Run end-to-end tests
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: '**junit*.xml'
        testRunTitle: TestRun ${{ parameters.name }} $(node_version)
