version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "electron"
      - match:
          dependency_name: "electron-settings"
      - match:
          dependency_name: "less"
