# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript
parameters:
  name: ''
  pool: ''
  xvfb: false
jobs:
  - job: ${{parameters.name}}
    pool: ${{parameters.pool}}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
    - ${{ if eq(parameters.xvfb, 'true') }}:
      - script: "Xvfb :99 -screen 0 1600x900x24 &"
    - script: |
        npm ci
        npm run package-ci
        npm run test-e2e
      displayName: 'Install dependencies and run packager'
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: '**junit*.xml'
        testRunTitle: TestRun ${{ parameters.name }} $(node_version)
