# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript
jobs:
- job: crowdin
  variables:
    CROWDIN_PROJECT_ID: $(CROWDIN_PROJECT_ID)
    CROWDIN_PROJECT_KEY: $(CROWDIN_PROJECT_KEY)
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '11.x'
    - script: npm install
      displayName: NPM install
    - script: npm run crowdin-update