# Packager. Runs on refs/tags/*
jobs:
- template: templates/package.yml
  parameters:
    pool: 'Hosted MacOS Preview'
    name: 'osx_package'
- template: templates/package.yml
  parameters:
    pool: 'Hosted Windows 2019 with VS2019'
    name: 'windows_package'
- template: templates/package.yml
  parameters:
    pool: 'Hosted Ubuntu 1604'
    name: 'linux_package'
