# Packager. Runs on refs/tags/*
jobs:
- template: templates/package.yml
  parameters:
    pool:
      vmImage: 'macOS-10.15'
    name: 'osx_package'
- template: templates/package.yml
  parameters:
    pool:
      vmImage: 'windows-2019'
    name: 'windows_package'
    buildScript: 'npx electron-builder build -w --ia32 --x64 --publish always'
- template: templates/package.yml
  parameters:
    pool:
      vmImage: 'ubuntu-18.04'
    name: 'linux_package'
