# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript
jobs:
- template: ci-jobs/build.yml
  parameters:
    pool: 'Hosted MacOS Preview'
    name: 'osx_package'
    script: |
      npx build --publish onTagOrDraft
      node ./sentry-set-version
      npm run sentry-release
- template: ci-jobs/build.yml
  parameters:
    pool: 'Hosted Windows 2019 with VS2019'
    name: 'windows_package'
    script: |
      npx build --publish onTagOrDraft
      node ./sentry-set-version
      npm run sentry-release
- template: ci-jobs/build.yml
  parameters:
    target: NSIS
    pool: 'Hosted Windows 2019 with VS2019'
    name: 'windows_package'
    script: |
      npx build --win nsis-web --publish onTagOrDraft
      node ./sentry-set-version
      npm run sentry-release
- template: ci-jobs/build.yml
  parameters:
    pool: 'Hosted Ubuntu 1604'
    name: 'linux_package'
    script: |
      npx build --publish onTagOrDraft
      node ./sentry-set-version
      npm run sentry-release