jobs:
  - job: CrowdinSync
    pool: 
      vmImage: "macOS 10.13"
    steps:
    - script: |
        git remote add triager https://triager:$GITHUB_TOKEN@github.com/appium/appium-desktop
        git checkout -b master
        git status
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
      displayName: Create Crowdin Sync branch
    - task: NodeTool@0
      inputs:
        versionSpec: '11.x'
    - script: npm install request bluebird asyncbox 
      displayName: Install dependencies
    - script: npm run crowdin-sync
      displayName: Crowdin Sync
      env:
        CROWDIN_PROJECT_KEY: $(CROWDIN_PROJECT_KEY)
    - script: |
        git commit -a -n -m 'Update translations'
        git push -u triager crowdin-sync-$(Build.BuildNumber)
        git status
      displayName: Commit Translation Changes